http://localhost:8080/home

### get test
http://localhost:8080/get?id=100&name=aaa&id=2

### Post test
POST http://localhost:8080/post HTTP/1.1
Content-Type: application/json

{
    "name": "zhangsan",
    "age": 22
} 